import { Type } from '@angular/core';
import { NgbDotField, NgbDotGrid, NgbEmbers, NgbLetterGlitch, NgbShapeGrid } from 'ng-bits';
import {
  NgbAurora,
  NgbFerrofluid,
  NgbGradientWaves,
  NgbGrainient,
  NgbIridescence,
  NgbLightPillar,
  NgbLightRays,
  NgbOrb,
  NgbOrbitalAtlas,
  NgbPixel,
  NgbPixelBlast,
  NgbPlasma,
  NgbPrism,
  NgbPrismaticCells,
  NgbSilk,
  NgbSoftAurora,
  NgbThreads,
} from 'ng-bits/ogl';
import { NgbDottedForms, NgbLiquidEther } from 'ng-bits/three';

/** One editable knob in the playground panel. */
export type Control =
  | { kind: 'number'; key: string; label: string; min: number; max: number; step: number }
  | { kind: 'color'; key: string; label: string }
  | { kind: 'colors'; key: string; label: string; count: number }
  | { kind: 'boolean'; key: string; label: string }
  | { kind: 'select'; key: string; label: string; options: readonly string[] };

export type Engine = 'OGL' | 'Three.js' | 'Canvas 2D';

export interface BackgroundEntry {
  slug: string;
  name: string;
  tagline: string;
  engine: Engine;
  component: Type<unknown>;
  /** Props used on the detail page and as the starting point for the panel. */
  defaults: Record<string, unknown>;
  /** Cheaper props for the gallery tiles, merged over `defaults`. */
  tile?: Record<string, unknown>;
  controls: Control[];
  /** Backdrop the background is composited over. */
  surface: string;
}

const num = (key: string, label: string, min: number, max: number, step = 0.01): Control => ({
  kind: 'number',
  key,
  label,
  min,
  max,
  step,
});

const bool = (key: string, label: string): Control => ({ kind: 'boolean', key, label });
const color = (key: string, label: string): Control => ({ kind: 'color', key, label });

export const BACKGROUNDS: readonly BackgroundEntry[] = [
  {
    slug: 'dotted-forms',
    name: 'Dotted Forms',
    tagline: 'Rotating point-shell sculptures with colour mapped across their faces.',
    engine: 'Three.js',
    component: NgbDottedForms,
    surface: 'bg-[#050508]',
    defaults: {
      shape: 'cube',
      colors: ['#E74C3C', '#F1C40F', '#2ECC71', '#3498DB', '#FFFFFF', '#F39C12'],
      density: 22,
      pointSize: 8,
      scale: 0.72,
      speed: 0.45,
      tilt: 0.5,
      mouseInteraction: true,
      mouseStrength: 0.42,
      opacity: 0.94,
      backgroundColor: '#050508',
      maxDpr: 1.5,
    },
    tile: { density: 15, pointSize: 7, maxDpr: 1 },
    controls: [
      {
        kind: 'select',
        key: 'shape',
        label: 'Shape',
        options: ['cube', 'sphere', 'torus', 'octahedron'],
      },
      { kind: 'colors', key: 'colors', label: 'Face colors', count: 6 },
      num('density', 'Density', 5, 36, 1),
      num('pointSize', 'Point size', 1, 24, 0.5),
      num('scale', 'Scale', 0.25, 2, 0.05),
      num('speed', 'Speed', 0, 3),
      num('tilt', 'Tilt', 0, 1.5),
      bool('mouseInteraction', 'Mouse parallax'),
      num('mouseStrength', 'Mouse strength', 0, 1.5),
      num('opacity', 'Opacity', 0, 1),
      color('backgroundColor', 'Background'),
    ],
  },
  {
    slug: 'embers',
    name: 'Embers',
    tagline: 'Small glowing sparks that rise, flicker and bend with the wind.',
    engine: 'Canvas 2D',
    component: NgbEmbers,
    surface: 'bg-black',
    defaults: {
      colors: ['#ffb15c', '#ff6b2c', '#ffe1a8'],
      count: 90,
      speed: 1,
      size: 1.6,
      glow: 1.2,
      turbulence: 0.8,
      wind: 0.15,
      spread: 0.8,
      opacity: 0.9,
    },
    tile: { count: 55, maxDpr: 1 },
    controls: [
      { kind: 'colors', key: 'colors', label: 'Colors', count: 3 },
      num('count', 'Count', 0, 300, 1),
      num('speed', 'Speed', 0, 3),
      num('size', 'Size', 0.25, 5, 0.05),
      num('glow', 'Glow', 0, 3),
      num('turbulence', 'Turbulence', 0, 3),
      num('wind', 'Wind', -2, 2, 0.05),
      num('spread', 'Spread', 0, 1),
      num('opacity', 'Opacity', 0, 1),
    ],
  },
  {
    slug: 'aurora',
    name: 'Aurora',
    tagline: 'A soft curtain anchored to the top edge, drifting on noise.',
    engine: 'OGL',
    component: NgbAurora,
    surface: 'bg-black',
    defaults: {
      colorStops: ['#7cff67', '#B497CF', '#5227FF'],
      amplitude: 1,
      blend: 0.5,
      speed: 1,
      intensity: 1,
    },
    controls: [
      { kind: 'colors', key: 'colorStops', label: 'Color stops', count: 3 },
      num('amplitude', 'Amplitude', 0, 3),
      num('blend', 'Blend', 0, 1),
      num('speed', 'Speed', 0, 4),
      num('intensity', 'Intensity', 0, 2),
    ],
  },
  {
    slug: 'gradient-waves',
    name: 'Gradient Waves',
    tagline: 'Rolling colour fields that dissolve into a distant haze.',
    engine: 'OGL',
    component: NgbGradientWaves,
    surface: 'bg-[#090611]',
    defaults: {
      horizonColor: '#5227FF',
      waveColor: '#FF9FFC',
      crestColor: '#FFFFFF',
      speed: 0.4,
      amplitude: 2.5,
      waveScale: 0.6,
      waveRatio: 0.9,
      swell: 35,
      turbulence: 20,
      tilt: 1.11,
      zoom: 1,
      height: 5.5,
      fogDepth: 15,
      detail: 'medium',
      brightness: 1,
      opacity: 1,
      mouseInteraction: true,
      parallaxStrength: 0.5,
      grain: true,
      grainIntensity: 0.05,
    },
    tile: { detail: 'low', grain: false, maxDpr: 1 },
    controls: [
      color('horizonColor', 'Horizon color'),
      color('waveColor', 'Wave color'),
      color('crestColor', 'Crest color'),
      num('speed', 'Speed', 0, 2),
      num('amplitude', 'Amplitude', 0, 6, 0.1),
      num('waveScale', 'Wave scale', 0.1, 2),
      num('waveRatio', 'Wave ratio', 0, 2),
      num('swell', 'Swell', 0, 80, 1),
      num('turbulence', 'Turbulence', 0, 60, 1),
      num('tilt', 'Tilt', 0.35, 1.48),
      num('zoom', 'Zoom', 0.35, 2.5),
      num('height', 'Horizon height', 1, 10, 0.1),
      num('fogDepth', 'Fog depth', 3, 30, 0.5),
      { kind: 'select', key: 'detail', label: 'Detail', options: ['low', 'medium', 'high'] },
      num('brightness', 'Brightness', 0, 3),
      num('opacity', 'Opacity', 0, 1),
      bool('mouseInteraction', 'Mouse parallax'),
      num('parallaxStrength', 'Parallax strength', 0, 2),
      bool('grain', 'Grain'),
      num('grainIntensity', 'Grain intensity', 0, 0.25, 0.005),
    ],
  },
  {
    slug: 'prismatic-cells',
    name: 'Prismatic Cells',
    tagline: 'Dark glass cells edged by a slowly shifting spectral refraction.',
    engine: 'OGL',
    component: NgbPrismaticCells,
    surface: 'bg-[#05040B]',
    defaults: {
      colors: ['#7C5CFF', '#38D7FF', '#FF6EDB'],
      backgroundColor: '#05040B',
      cellScale: 8,
      speed: 0.32,
      edgeWidth: 0.075,
      refraction: 0.78,
      glow: 0.85,
      mouseInteraction: true,
      mouseStrength: 0.72,
      opacity: 1,
      maxDpr: 1.5,
    },
    tile: { cellScale: 6.5, maxDpr: 1 },
    controls: [
      { kind: 'colors', key: 'colors', label: 'Colors', count: 3 },
      color('backgroundColor', 'Background'),
      num('cellScale', 'Cell scale', 2, 20, 0.25),
      num('speed', 'Speed', 0, 3),
      num('edgeWidth', 'Edge width', 0.005, 0.28, 0.005),
      num('refraction', 'Refraction', 0, 1.5),
      num('glow', 'Glow', 0, 3),
      bool('mouseInteraction', 'Mouse'),
      num('mouseStrength', 'Mouse strength', 0, 2),
      num('opacity', 'Opacity', 0, 1),
    ],
  },
  {
    slug: 'soft-aurora',
    name: 'Soft Aurora',
    tagline: 'Three oversized blobs drifting on Lissajous paths.',
    engine: 'OGL',
    component: NgbSoftAurora,
    surface: 'bg-ink-950',
    defaults: {
      colors: ['#ff7ab6', '#7b9cff', '#7ce7d1'],
      speed: 1,
      softness: 0.65,
      intensity: 1,
      scale: 1,
    },
    controls: [
      { kind: 'colors', key: 'colors', label: 'Colors', count: 3 },
      num('speed', 'Speed', 0, 4),
      num('softness', 'Softness', 0, 1),
      num('intensity', 'Intensity', 0, 2),
      num('scale', 'Scale', 0.3, 3),
    ],
  },
  {
    slug: 'iridescence',
    name: 'Iridescence',
    tagline: 'Thin-film interference bands folding over each other.',
    engine: 'OGL',
    component: NgbIridescence,
    surface: 'bg-black',
    defaults: {
      color: '#8099cc',
      speed: 1,
      amplitude: 0.1,
      saturation: 1,
      mouseReact: true,
    },
    controls: [
      color('color', 'Color'),
      num('speed', 'Speed', 0, 4),
      num('amplitude', 'Mouse amplitude', 0, 1),
      num('saturation', 'Saturation', 0, 2),
      bool('mouseReact', 'Mouse'),
    ],
  },
  {
    slug: 'orb',
    name: 'Orb',
    tagline: 'A spectral shell that wakes and folds open under the pointer.',
    engine: 'OGL',
    component: NgbOrb,
    surface: 'bg-black',
    defaults: {
      hue: 0,
      hoverIntensity: 0.2,
      rotateOnHover: true,
      forceHoverState: false,
      backgroundColor: '#000000',
    },
    tile: { hoverIntensity: 0.75, maxDpr: 1 },
    controls: [
      num('hue', 'Hue shift', 0, 360, 1),
      num('hoverIntensity', 'Hover intensity', 0, 3),
      bool('rotateOnHover', 'Rotate on hover'),
      bool('forceHoverState', 'Force hover state'),
      color('backgroundColor', 'Background'),
    ],
  },
  {
    slug: 'orbital-atlas',
    name: 'Orbital Atlas',
    tagline: 'Interrupted orbital arcs and satellites in a quiet diagrammatic field.',
    engine: 'OGL',
    component: NgbOrbitalAtlas,
    surface: 'bg-[#080811]',
    defaults: {
      colors: ['#9dd6ff', '#b7a7ff', '#ff9fc9'],
      backgroundColor: '#080811',
      orbitCount: 5,
      speed: 0.3,
      eccentricity: 0.46,
      arcLength: 0.64,
      lineWidth: 0.004,
      glow: 0.7,
      mouseInteractive: true,
      mouseParallax: 0.035,
      maxDpr: 1.5,
    },
    tile: { orbitCount: 4, maxDpr: 1 },
    controls: [
      { kind: 'colors', key: 'colors', label: 'Colors', count: 3 },
      color('backgroundColor', 'Background'),
      num('orbitCount', 'Orbit count', 2, 7, 1),
      num('speed', 'Speed', 0, 2),
      num('eccentricity', 'Eccentricity', 0, 0.82),
      num('arcLength', 'Arc length', 0.08, 1),
      num('lineWidth', 'Line width', 0.0005, 0.03, 0.0005),
      num('glow', 'Glow', 0, 2),
      bool('mouseInteractive', 'Mouse'),
      num('mouseParallax', 'Mouse parallax', 0, 0.15, 0.005),
    ],
  },
  {
    slug: 'prism',
    name: 'Prism',
    tagline: 'Diffuse spectrum light resolving into a bright tilted caustic.',
    engine: 'OGL',
    component: NgbPrism,
    surface: 'bg-black',
    defaults: {
      animation: 'drift',
      colors: ['#52d9ff', '#8b7cff', '#ff9c69'],
      backgroundColor: '#02030a',
      scale: 1,
      intensity: 1.35,
      timeScale: 0.5,
      glow: 1,
      bloom: 1,
      hueShift: 0,
      dispersion: 0.6,
      noise: 0.025,
      maxDpr: 1.5,
    },
    tile: { maxDpr: 1 },
    controls: [
      {
        kind: 'select',
        key: 'animation',
        label: 'Animation',
        options: ['drift', 'hover', 'still'],
      },
      { kind: 'colors', key: 'colors', label: 'Light colours', count: 3 },
      color('backgroundColor', 'Background'),
      num('scale', 'Scale', 0.5, 2.5, 0.05),
      num('intensity', 'Exposure', 0, 3, 0.05),
      num('timeScale', 'Time scale', 0, 3),
      num('glow', 'Glow', 0, 3),
      num('bloom', 'Caustic bloom', 0, 3),
      num('dispersion', 'Dispersion', 0, 1),
      num('hueShift', 'Hue shift', 0, 6.28),
      num('noise', 'Noise', 0, 0.15, 0.005),
      num('hoverStrength', 'Hover strength', 0, 1),
    ],
  },
  {
    slug: 'ferrofluid',
    name: 'Ferrofluid',
    tagline: 'Glowing iso-contours tracing two fused bodies of fluid.',
    engine: 'OGL',
    component: NgbFerrofluid,
    surface: 'bg-black',
    defaults: {
      colors: ['#ffffff'],
      backgroundColor: '#000000',
      speed: 0.5,
      scale: 1.6,
      turbulence: 1,
      fluidity: 0.1,
      rimWidth: 0.2,
      sharpness: 2.5,
      shimmer: 1.5,
      glow: 2,
      bands: 4,
      flowDirection: 'down',
      mouseInteraction: true,
      mouseStrength: 1,
      mouseRadius: 0.35,
    },
    tile: { maxDpr: 1 },
    controls: [
      { kind: 'colors', key: 'colors', label: 'Rim colors', count: 3 },
      color('backgroundColor', 'Background'),
      num('speed', 'Speed', 0, 3),
      num('scale', 'Scale', 0.3, 5),
      num('turbulence', 'Turbulence', 0, 3),
      num('fluidity', 'Fluidity', 0.01, 1),
      num('rimWidth', 'Rim width', 0.01, 1),
      num('sharpness', 'Sharpness', 0.2, 8),
      num('shimmer', 'Shimmer', 0, 2),
      num('glow', 'Glow', 0, 5),
      num('bands', 'Contours', 1, 12, 1),
      {
        kind: 'select',
        key: 'flowDirection',
        label: 'Flow',
        options: ['down', 'up', 'left', 'right'],
      },
      bool('mouseInteraction', 'Magnetic cursor'),
      num('mouseStrength', 'Mouse strength', 0, 3),
      num('mouseRadius', 'Mouse radius', 0.05, 1),
    ],
  },
  {
    slug: 'silk',
    name: 'Silk',
    tagline: 'A rippling satin weave. Opaque, fills the canvas.',
    engine: 'OGL',
    component: NgbSilk,
    surface: 'bg-black',
    defaults: { color: '#7b7481', speed: 5, scale: 1, rotation: 0, grain: 1.5 },
    controls: [
      color('color', 'Color'),
      num('speed', 'Speed', 0, 20, 0.1),
      num('scale', 'Scale', 0.2, 4),
      num('rotation', 'Rotation', 0, 6.28),
      num('grain', 'Grain', 0, 4),
    ],
  },
  {
    slug: 'plasma',
    name: 'Plasma',
    tagline: 'Four interfering sine fronts, tintable to your palette.',
    engine: 'OGL',
    component: NgbPlasma,
    surface: 'bg-black',
    defaults: {
      color: '#ff6b35',
      tint: 0,
      speed: 1,
      scale: 1,
      opacity: 1,
      direction: 'forward',
      mouseInteractive: true,
      mouseInfluence: 0.4,
    },
    controls: [
      color('color', 'Tint color'),
      num('tint', 'Tint amount', 0, 1),
      num('speed', 'Speed', 0, 4),
      num('scale', 'Scale', 0.2, 3),
      num('opacity', 'Opacity', 0, 1),
      {
        kind: 'select',
        key: 'direction',
        label: 'Direction',
        options: ['forward', 'reverse', 'pingpong'],
      },
      bool('mouseInteractive', 'Mouse'),
      num('mouseInfluence', 'Mouse influence', 0, 1),
    ],
  },
  {
    slug: 'grainient',
    name: 'Grainient',
    tagline: 'Domain-warped mesh gradient with film grain.',
    engine: 'OGL',
    component: NgbGrainient,
    surface: 'bg-black',
    defaults: {
      colors: ['#0f0c29', '#302b63', '#24243e'],
      speed: 1,
      warp: 0.6,
      scale: 1.4,
      grain: 0.06,
      grainScale: 0.9,
      angle: 0,
    },
    controls: [
      { kind: 'colors', key: 'colors', label: 'Colors', count: 4 },
      num('speed', 'Speed', 0, 4),
      num('warp', 'Warp', 0, 2),
      num('scale', 'Scale', 0.2, 4),
      num('grain', 'Grain', 0, 0.3, 0.005),
      num('grainScale', 'Grain scale', 0.1, 3),
      num('angle', 'Angle', 0, 6.28),
    ],
  },
  {
    slug: 'light-rays',
    name: 'Light Rays',
    tagline: 'Volumetric god rays from a configurable origin.',
    engine: 'OGL',
    component: NgbLightRays,
    surface: 'bg-black',
    defaults: {
      origin: 'top-center',
      color: '#c8b4ff',
      speed: 1,
      spread: 0.6,
      rayLength: 1.2,
      fadeDistance: 1.4,
      pulsating: 0,
      noiseAmount: 0.1,
      saturation: 1,
      intensity: 2.5,
      followMouse: true,
      mouseInfluence: 0.35,
    },
    controls: [
      {
        kind: 'select',
        key: 'origin',
        label: 'Origin',
        options: [
          'top-center',
          'top-left',
          'top-right',
          'left',
          'right',
          'bottom-center',
          'bottom-left',
          'bottom-right',
        ],
      },
      color('color', 'Color'),
      num('speed', 'Speed', 0, 4),
      num('spread', 'Spread', 0, 1),
      num('rayLength', 'Ray length', 0.1, 3),
      num('fadeDistance', 'Fade distance', 0.2, 3),
      num('pulsating', 'Pulsating', 0, 1),
      num('noiseAmount', 'Noise', 0, 1),
      num('saturation', 'Saturation', 0, 1),
      num('intensity', 'Intensity', 0, 6),
      bool('followMouse', 'Follow mouse'),
    ],
  },
  {
    slug: 'light-pillar',
    name: 'Light Pillar',
    tagline: 'Vertical light shafts with drifting dust and floor pools.',
    engine: 'OGL',
    component: NgbLightPillar,
    surface: 'bg-black',
    defaults: {
      count: 3,
      colors: ['#00d4ff', '#7b61ff', '#ff5ea8'],
      speed: 1,
      width: 0.05,
      height: 0.9,
      intensity: 1,
      flicker: 0.15,
      spread: 0.7,
      floorGlow: 0.6,
    },
    controls: [
      num('count', 'Count', 1, 8, 1),
      { kind: 'colors', key: 'colors', label: 'Colors', count: 3 },
      num('speed', 'Speed', 0, 4),
      num('width', 'Width', 0.005, 0.3, 0.005),
      num('height', 'Height', 0.1, 1),
      num('intensity', 'Intensity', 0, 3),
      num('flicker', 'Flicker', 0, 1),
      num('spread', 'Spread', 0, 1.5),
      num('floorGlow', 'Floor glow', 0, 2),
    ],
  },
  {
    slug: 'liquid-ether',
    name: 'Liquid Ether',
    tagline: 'A real GPU fluid solver — advection, pressure, vorticity.',
    engine: 'Three.js',
    component: NgbLiquidEther,
    surface: 'bg-black',
    defaults: {
      colors: ['#5227ff', '#ff9ffd', '#b19eef'],
      simResolution: 128,
      dyeResolution: 512,
      force: 1,
      cursorSize: 0.2,
      pressureIterations: 20,
      curl: 24,
      dyeDecay: 0.9,
      velocityDecay: 0.25,
      opacity: 1,
      autoDemo: true,
    },
    tile: { simResolution: 64, dyeResolution: 256, pressureIterations: 12, maxDpr: 1 },
    controls: [
      { kind: 'colors', key: 'colors', label: 'Colors', count: 3 },
      num('force', 'Force', 0, 4),
      num('cursorSize', 'Cursor size', 0.02, 1),
      num('curl', 'Curl', 0, 60, 1),
      num('dyeDecay', 'Dye decay', 0, 4),
      num('velocityDecay', 'Velocity decay', 0, 4),
      num('pressureIterations', 'Pressure iters', 4, 40, 1),
      num('simResolution', 'Sim resolution', 32, 256, 32),
      num('opacity', 'Opacity', 0, 1),
      bool('autoDemo', 'Auto demo'),
    ],
  },
  {
    slug: 'pixel',
    name: 'Pixel',
    tagline: 'A noise field resolved through an 8x8 Bayer dither.',
    engine: 'OGL',
    component: NgbPixel,
    surface: 'bg-black',
    defaults: {
      variant: 'square',
      color: '#B497CF',
      backgroundColor: '#000000',
      transparent: false,
      pixelSize: 4,
      patternScale: 2,
      patternDensity: 1,
      pixelSizeJitter: 0,
      speed: 0.5,
      edgeFade: 0.25,
      noiseAmount: 0,
      enableRipples: true,
      rippleSpeed: 0.5,
      rippleThickness: 0.08,
      rippleIntensityScale: 1,
      liquid: false,
      liquidStrength: 0.35,
      liquidRadius: 0.3,
      liquidWobbleSpeed: 3,
    },
    controls: [
      {
        kind: 'select',
        key: 'variant',
        label: 'Variant',
        options: ['square', 'circle', 'triangle', 'diamond'],
      },
      color('color', 'Color'),
      num('pixelSize', 'Pixel size', 2, 24, 1),
      num('patternScale', 'Pattern scale', 0.2, 8),
      num('patternDensity', 'Pattern density', 0.1, 3),
      num('pixelSizeJitter', 'Jitter', 0, 1),
      num('speed', 'Speed', 0, 4),
      num('edgeFade', 'Edge fade', 0, 0.5),
      num('noiseAmount', 'Noise', 0, 1),
      bool('enableRipples', 'Ripples on click'),
      num('rippleSpeed', 'Ripple speed', 0.05, 2),
      num('rippleThickness', 'Ripple thickness', 0.005, 0.3, 0.005),
      bool('liquid', 'Liquid'),
      num('liquidStrength', 'Liquid strength', 0, 1),
      bool('transparent', 'Transparent'),
    ],
  },
  {
    slug: 'pixel-blast',
    name: 'Pixel Blast',
    tagline: 'The softer sibling: glyphs grow and shrink instead of toggling.',
    engine: 'OGL',
    component: NgbPixelBlast,
    surface: 'bg-ink-950',
    defaults: {
      shape: 'square',
      color: '#b19eef',
      pixelSize: 6,
      speed: 1,
      density: 3,
      threshold: 0.3,
      edgeFade: 0.1,
      rippleOnClick: true,
      rippleSpeed: 0.6,
      rippleWidth: 0.06,
      rippleStrength: 0.9,
      rippleDecay: 1.2,
    },
    controls: [
      {
        kind: 'select',
        key: 'shape',
        label: 'Shape',
        options: ['square', 'circle', 'triangle', 'diamond'],
      },
      color('color', 'Color'),
      num('pixelSize', 'Pixel size', 2, 32, 1),
      num('speed', 'Speed', 0, 4),
      num('density', 'Density', 0.5, 12),
      num('threshold', 'Threshold', 0, 1),
      num('edgeFade', 'Edge fade', 0, 0.5),
      bool('rippleOnClick', 'Ripple on click'),
      num('rippleSpeed', 'Ripple speed', 0.05, 2),
      num('rippleWidth', 'Ripple width', 0.005, 0.3, 0.005),
      num('rippleStrength', 'Ripple strength', 0, 3),
    ],
  },
  {
    slug: 'shape-grid',
    name: 'Shape Grid',
    tagline: 'A drifting grid of outlined tiles that fill under the pointer.',
    engine: 'Canvas 2D',
    component: NgbShapeGrid,
    surface: 'bg-ink-950',
    defaults: {
      shape: 'square',
      direction: 'diagonal',
      squareSize: 40,
      speed: 0.5,
      borderColor: '#2F293A',
      hoverFillColor: '#222222',
      hoverTrailAmount: 0,
      vignetteColor: '#060010',
    },
    controls: [
      {
        kind: 'select',
        key: 'shape',
        label: 'Shape',
        options: ['square', 'hexagon', 'circle', 'triangle'],
      },
      {
        kind: 'select',
        key: 'direction',
        label: 'Direction',
        options: ['diagonal', 'up', 'right', 'down', 'left'],
      },
      num('squareSize', 'Tile size', 12, 120, 1),
      num('speed', 'Speed', 0, 4),
      color('borderColor', 'Border'),
      color('hoverFillColor', 'Hover fill'),
      num('hoverTrailAmount', 'Hover trail', 0, 20, 1),
      color('vignetteColor', 'Vignette'),
    ],
  },
  {
    slug: 'dot-field',
    name: 'Dot Field',
    tagline: 'A fine gradient dot grid with a lens bulge under the cursor.',
    engine: 'Canvas 2D',
    component: NgbDotField,
    surface: 'bg-ink-950',
    defaults: {
      dotRadius: 1.5,
      dotSpacing: 14,
      cursorRadius: 500,
      cursorForce: 0.1,
      bulgeOnly: true,
      bulgeStrength: 67,
      glowRadius: 160,
      glowColor: '#120F17',
      sparkle: false,
      waveAmplitude: 0,
      gradientFrom: '#A855F7',
      gradientTo: '#B497CF',
    },
    controls: [
      num('dotRadius', 'Dot radius', 0.5, 6, 0.1),
      num('dotSpacing', 'Spacing', 6, 60, 1),
      color('gradientFrom', 'Gradient from'),
      color('gradientTo', 'Gradient to'),
      num('cursorRadius', 'Cursor radius', 50, 900, 10),
      bool('bulgeOnly', 'Bulge only'),
      num('bulgeStrength', 'Bulge strength', 0, 200, 1),
      num('cursorForce', 'Cursor force', 0, 1),
      num('glowRadius', 'Glow radius', 0, 500, 10),
      color('glowColor', 'Glow color'),
      bool('sparkle', 'Sparkle'),
      num('waveAmplitude', 'Wave amplitude', 0, 20, 0.5),
    ],
  },
  {
    slug: 'dot-grid',
    name: 'Dot Grid',
    tagline: 'Springy dots that scatter on click and settle back.',
    engine: 'Canvas 2D',
    component: NgbDotGrid,
    surface: 'bg-ink-950',
    defaults: {
      dotSize: 4,
      gap: 24,
      baseColor: '#27272a',
      activeColor: '#5227ff',
      proximity: 140,
      shockRadius: 240,
      shockStrength: 900,
      stiffness: 120,
      damping: 12,
      repel: false,
    },
    controls: [
      num('dotSize', 'Dot size', 1, 16, 0.5),
      num('gap', 'Gap', 6, 80, 1),
      color('baseColor', 'Base'),
      color('activeColor', 'Active'),
      num('proximity', 'Proximity', 20, 400, 5),
      num('shockRadius', 'Shock radius', 0, 600, 10),
      num('shockStrength', 'Shock strength', 0, 3000, 50),
      num('stiffness', 'Stiffness', 10, 400, 5),
      num('damping', 'Damping', 1, 40, 0.5),
      bool('repel', 'Repel on hover'),
    ],
  },
  {
    slug: 'letter-glitch',
    name: 'Letter Glitch',
    tagline: 'A terminal wall of characters reshuffling itself.',
    engine: 'Canvas 2D',
    component: NgbLetterGlitch,
    surface: 'bg-black',
    defaults: {
      colors: ['#2b4539', '#61dca3', '#61b3dc'],
      charWidth: 10,
      charHeight: 20,
      fontSize: 16,
      glitchRate: 0.35,
      smooth: true,
      fadeDuration: 0.5,
      outerVignette: true,
      centerVignette: false,
      backgroundColor: '#000000',
    },
    controls: [
      { kind: 'colors', key: 'colors', label: 'Colors', count: 3 },
      num('charWidth', 'Char width', 4, 30, 1),
      num('charHeight', 'Char height', 8, 48, 1),
      num('fontSize', 'Font size', 6, 40, 1),
      num('glitchRate', 'Glitch rate', 0, 3),
      bool('smooth', 'Smooth fade'),
      num('fadeDuration', 'Fade duration', 0.05, 2),
      bool('outerVignette', 'Outer vignette'),
      bool('centerVignette', 'Center vignette'),
    ],
  },
  {
    slug: 'threads',
    name: 'Threads',
    tagline: 'A fan of glowing filaments that parts around the pointer.',
    engine: 'OGL',
    component: NgbThreads,
    surface: 'bg-black',
    defaults: {
      color: '#ffffff',
      amplitude: 1,
      spread: 0.55,
      thickness: 0.004,
      speed: 1,
      mouseInteractive: true,
      mouseInfluence: 1,
    },
    controls: [
      color('color', 'Color'),
      num('amplitude', 'Amplitude', 0, 3),
      num('spread', 'Spread', 0, 1.5),
      num('thickness', 'Thickness', 0.0005, 0.02, 0.0005),
      num('speed', 'Speed', 0, 4),
      bool('mouseInteractive', 'Mouse'),
      num('mouseInfluence', 'Mouse influence', 0, 3),
    ],
  },
];

export function findBackground(slug: string): BackgroundEntry | undefined {
  return BACKGROUNDS.find((entry) => entry.slug === slug);
}
